import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { fmtKES, fmtDate } from "./finance";

export type MonthReport = {
  period: string;               // e.g. "2026-05"
  periodLabel: string;          // e.g. "May 2026"
  generatedBy: string;
  generatedAt: string;          // ISO
  income: number;
  expense: number;
  fees: number;
  net: number;
  txCount: number;
  byCategory: { name: string; value: number }[];
  topCategory?: string;
  insights: string[];
  nextMonthTips: string[];
};

export function downloadMonthReport(r: MonthReport) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();

  // Header band
  doc.setFillColor(1, 117, 194);
  doc.rect(0, 0, W, 70, "F");
  doc.setTextColor(255);
  doc.setFontSize(20); doc.setFont("helvetica", "bold");
  doc.text("FinTask — Monthly Report", 32, 32);
  doc.setFontSize(12); doc.setFont("helvetica", "normal");
  doc.text(r.periodLabel, 32, 52);

  // Meta block
  doc.setTextColor(80);
  doc.setFontSize(9);
  const gen = new Date(r.generatedAt);
  doc.text(`Generated by: ${r.generatedBy}`, 32, 92);
  doc.text(`Generated on: ${fmtDate(gen)} ${gen.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })}`, 32, 106);
  doc.text(`Transactions: ${r.txCount}`, 32, 120);

  // Summary table
  autoTable(doc, {
    startY: 140,
    head: [["Metric", "Amount"]],
    body: [
      ["Income", fmtKES(r.income)],
      ["Expenses", fmtKES(r.expense)],
      ["Transaction fees", fmtKES(r.fees)],
      ["Net", fmtKES(r.net)],
    ],
    theme: "grid",
    headStyles: { fillColor: [1, 117, 194] },
    styles: { fontSize: 10 },
  });

  // Category breakdown
  const catStart = (doc as any).lastAutoTable.finalY + 20;
  doc.setTextColor(30); doc.setFontSize(12); doc.setFont("helvetica", "bold");
  doc.text("Spending by category", 32, catStart);
  autoTable(doc, {
    startY: catStart + 8,
    head: [["Category", "Amount", "% of expenses"]],
    body: r.byCategory.length
      ? r.byCategory.map(c => [c.name, fmtKES(c.value), r.expense > 0 ? ((c.value / r.expense) * 100).toFixed(1) + "%" : "—"])
      : [["No expenses recorded", "—", "—"]],
    theme: "striped",
    headStyles: { fillColor: [52, 168, 83] },
    styles: { fontSize: 10 },
  });

  // Insights
  let y = (doc as any).lastAutoTable.finalY + 24;
  if (y > 720) { doc.addPage(); y = 60; }
  doc.setFontSize(12); doc.setFont("helvetica", "bold"); doc.setTextColor(30);
  doc.text("This month's insights", 32, y); y += 14;
  doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(60);
  (r.insights.length ? r.insights : ["No standout patterns."]).forEach(line => {
    const wrapped = doc.splitTextToSize(`• ${line}`, W - 64);
    doc.text(wrapped, 32, y); y += wrapped.length * 12 + 2;
  });

  y += 10;
  if (y > 720) { doc.addPage(); y = 60; }
  doc.setFontSize(12); doc.setFont("helvetica", "bold"); doc.setTextColor(30);
  doc.text("Recommendations for next month", 32, y); y += 14;
  doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(60);
  (r.nextMonthTips.length ? r.nextMonthTips : ["Keep tracking consistently."]).forEach(line => {
    const wrapped = doc.splitTextToSize(`→ ${line}`, W - 64);
    doc.text(wrapped, 32, y); y += wrapped.length * 12 + 2;
  });

  // Footer
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8); doc.setTextColor(140);
    doc.text(`FinTask · Confidential · Page ${i} of ${pages}`, 32, doc.internal.pageSize.getHeight() - 18);
  }

  doc.save(`FinTask-Report-${r.period}.pdf`);
}

export function buildInsights(income: number, expense: number, byCat: { name: string; value: number }[], prevExpense?: number) {
  const out: string[] = [];
  const net = income - expense;
  if (income > 0) out.push(`Save rate: ${((net / income) * 100).toFixed(1)}% of income kept.`);
  if (byCat[0]) out.push(`Top spend category was ${byCat[0].name} at ${fmtKES(byCat[0].value)} (${expense > 0 ? ((byCat[0].value / expense) * 100).toFixed(0) : 0}% of expenses).`);
  if (byCat[1]) out.push(`Runner-up: ${byCat[1].name} — ${fmtKES(byCat[1].value)}.`);
  if (prevExpense !== undefined && prevExpense > 0) {
    const diff = ((expense - prevExpense) / prevExpense) * 100;
    out.push(`Spending was ${diff >= 0 ? "up" : "down"} ${Math.abs(diff).toFixed(1)}% vs the previous month.`);
  }
  if (net < 0) out.push("You spent more than you earned this month.");
  return out;
}

export function buildTips(income: number, expense: number, byCat: { name: string; value: number }[]) {
  const tips: string[] = [];
  if (byCat[0] && expense > 0 && byCat[0].value / expense > 0.35) {
    tips.push(`${byCat[0].name} takes over a third of spend — consider a monthly cap next month.`);
  }
  const net = income - expense;
  if (income > 0 && net / income < 0.1) tips.push("Aim for at least a 10% save rate — automate a transfer to savings on payday.");
  if (net < 0) tips.push("Trim the two largest categories by 15% to bring next month back to positive.");
  if (byCat.length > 5) tips.push("You spent across many categories — try setting a weekly cash allowance for discretionary items.");
  tips.push("Review recurring subscriptions and cancel any you haven't used in the last 30 days.");
  return tips;
}
